version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/pawelhenek/golang-playground
    steps:
      - checkout
      - run: go run src/github.com/pawelhenek/go-by-example/environment-variables.go
